Repository gen-classroom/projet-besseau_cerottini_maziero_ogi, pull requests merged in 2021-05, with the labels that each got.

#63 Change in Init
  src/main/java/ch/heig_vd/app/command/Build.java
  src/main/java/ch/heig_vd/app/command/Init.java
  src/main/java/ch/heig_vd/app/generator/ConfigGenerator.java
  src/main/java/ch/heig_vd/app/generator/TemplateGenerator.java
  src/test/java/ch/heig_vd/app/InitTest.java
Labels: Feature, enhancement, good first issue

#62 Template interpreter
  pom.xml
  src/main/java/ch/heig_vd/app/Main.java
  src/main/java/ch/heig_vd/app/command/Build.java
  src/main/java/ch/heig_vd/app/command/Clean.java
  src/main/java/ch/heig_vd/app/command/Init.java
  src/main/java/ch/heig_vd/app/converter/Converter.java
  src/main/java/ch/heig_vd/app/converter/interpreter/TemplateInterpreter.java
  src/main/java/ch/heig_vd/app/converter/interpreter/helper/LinkAttributeProvider.java
  src/main/java/ch/heig_vd/app/converter/interpreter/helper/MarkdownHelper.java
  src/main/java/ch/heig_vd/app/converter/parser/JsonParser.java
  src/main/java/ch/heig_vd/app/converter/parser/JsonParserVisitor.java
  src/main/java/ch/heig_vd/app/converter/parser/PageParser.java
  src/main/java/ch/heig_vd/app/converter/utils/Metadata.java
  src/main/java/ch/heig_vd/app/errorHandler/PrintExceptionMessageHandler.java
  src/main/java/ch/heig_vd/app/errorHandler/ShortErrorMessageHandler.java
  src/main/java/ch/heig_vd/app/generator/TemplateGenerator.java
  src/main/java/ch/heig_vd/app/utils/Converter.java
  src/main/java/ch/heig_vd/app/utils/PageParser.java
  src/main/resources/version.txt
  src/test/java/ch/heig_vd/app/command/BuildTest.java
  src/test/java/ch/heig_vd/app/command/CleanTest.java
  src/test/java/ch/heig_vd/app/command/InitTest.java
  src/test/java/ch/heig_vd/app/command/MainTest.java
  src/test/java/ch/heig_vd/app/converter/ConverterTest.java
  src/test/java/ch/heig_vd/app/converter/interpreter/TemplateInterpreterTest.java
  src/test/java/ch/heig_vd/app/converter/parser/JsonParserTest.java
  src/test/java/ch/heig_vd/app/converter/parser/PageParserTest.java
  src/test/java/ch/heig_vd/app/utils/ConverterTest.java
  src/test/java/ch/heig_vd/app/utils/PageParserTest.java
Labels: Feature, In Progress, To review, enhancement

#68 Create CD.yaml
  .github/workflows/CD.yaml
Labels: In Progress

#65 Implement Serve
  src/main/java/ch/heig_vd/app/command/Serve.java
  src/test/java/ch/heig_vd/app/ServeTest.java
Labels: Feature, In Progress, enhancement

#77 Modified structure of test
  src/test/java/ch/heig_vd/app/command/ServeTest.java
Labels: bug

#89 Started implementing file watcher
  pom.xml
  src/main/java/ch/heig_vd/app/fileWatcher/FileWatcher.java
  src/main/java/ch/heig_vd/app/fileWatcher/FileWatcherVisitor.java
  src/test/java/ch/heig_vd/app/fileWatcher/FileWatcherTest.java
Labels: To review

#93 Added fileWatcher into build
  src/main/java/ch/heig_vd/app/command/Build.java
  src/main/java/ch/heig_vd/app/fileWatcher/FileWatcher.java
  src/test/java/ch/heig_vd/app/command/BuildTest.java
  src/test/java/ch/heig_vd/app/fileWatcher/FileWatcherTest.java
Labels: To review

#91 Fb new serve
  doc/Schema.sly
  doc/Structure.svg
  doc/struct.png
  pom.xml
  src/main/java/ch/heig_vd/app/command/Build.java
  src/main/java/ch/heig_vd/app/command/Serve.java
  src/main/java/ch/heig_vd/app/fileWatcher/FileWatcher.java
  src/test/java/ch/heig_vd/app/command/BuildTest.java
  src/test/java/ch/heig_vd/app/converter/interpreter/TemplateInterpreterTest.java
  src/test/java/ch/heig_vd/app/fileWatcher/FileWatcherTest.java
Labels: Feature, In Progress, enhancement

#95 Integrate fileWatcher into serve
  src/main/java/ch/heig_vd/app/command/Build.java
  src/main/java/ch/heig_vd/app/command/Serve.java
Labels: To review

#92 Fb javadoc
  pom.xml
Labels: Feature, To review, documentation

#97 Added doc
  src/main/java/ch/heig_vd/app/Main.java
  src/main/java/ch/heig_vd/app/command/Build.java
  src/main/java/ch/heig_vd/app/command/Clean.java
  src/main/java/ch/heig_vd/app/command/Init.java
  src/main/java/ch/heig_vd/app/command/Serve.java
  src/main/java/ch/heig_vd/app/converter/Converter.java
  src/main/java/ch/heig_vd/app/converter/interpreter/TemplateInterpreter.java
  src/main/java/ch/heig_vd/app/converter/interpreter/helper/LinkAttributeProvider.java
  src/main/java/ch/heig_vd/app/converter/interpreter/helper/MarkdownHelper.java
  src/main/java/ch/heig_vd/app/converter/parser/JsonParser.java
  src/main/java/ch/heig_vd/app/converter/parser/PageParser.java
  src/main/java/ch/heig_vd/app/converter/utils/Metadata.java
  src/main/java/ch/heig_vd/app/errorHandler/PrintExceptionMessageHandler.java
  src/main/java/ch/heig_vd/app/errorHandler/ShortErrorMessageHandler.java
  src/main/java/ch/heig_vd/app/generator/ConfigGenerator.java
  src/main/java/ch/heig_vd/app/generator/TemplateGenerator.java
Labels: To review

#98 Fb infinite loop
  src/main/java/ch/heig_vd/app/command/Build.java
  src/main/java/ch/heig_vd/app/command/Serve.java
  src/main/java/ch/heig_vd/app/command/utils/ExitHandler.java
  src/main/java/ch/heig_vd/app/fileWatcher/FileWatcher.java
  src/test/java/ch/heig_vd/app/command/BuildTest.java
Labels: To review, bug

#99 Benchmark template interpreter and converter
  benchmark/example/config.json
  benchmark/example/template/default.html
  benchmark/example/template/meta.html
  benchmark/inputConverter.md
  benchmark/inputTemplate
  pom.xml
  src/benchmark/java/benchmark/Benchmark.java
  src/benchmark/java/benchmark/BenchmarkConverter.java
  src/benchmark/java/benchmark/BenchmarkTemplateInterpreter.java
  src/benchmark/java/benchmark/BenchmarkTemplateInterpreterWithMeta.java
  src/main/java/ch/heig_vd/app/command/Build.java
Labels: To review, documentation
